
import Navbar from "@/components/Navbar";
import "./globals.css";

import { Toaster } from "sonner";
import Footer from "@/components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
     <body className="bg-base text-black">
       <Navbar/>{children}
     <Toaster offset={80}
  position="top-center"
/>
<Footer/>
       </body>
    
    </html>
  );
}
